# Generated by Django 3.0.9 on 2020-12-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Nom')),
                ('music_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_library.MusicScore')),
            ],
        ),
    ]
