# Generated by Django 3.0.9 on 2020-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0004_stand_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('name', 'music_score'), name='unique_score_instrument_name'),
        ),
        migrations.AddConstraint(
            model_name='stand',
            constraint=models.UniqueConstraint(fields=('name', 'instrument'), name='unique_instrument_stand_name'),
        ),
    ]
