# Generated by Django 3.0.9 on 2021-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210303_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Administrateur'), (2, 'Modérateur partothèque'), (3, 'Modérateur photothèque'), (4, 'Modérateur évènements'), (5, 'Secrétaire'), (6, 'Membre du bureau'), (7, 'Musicien')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='user.Role'),
        ),
    ]
