# Generated by Django 3.0.9 on 2021-03-25 13:08

from django.db import migrations


def generates_roles(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Role.objects.get_or_create(id=1)
    Role.objects.get_or_create(id=2)
    Role.objects.get_or_create(id=3)
    Role.objects.get_or_create(id=4)
    Role.objects.get_or_create(id=5)
    Role.objects.get_or_create(id=6)
    Role.objects.get_or_create(id=7)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role'),
    ]

    operations = [
        migrations.RunPython(generates_roles),
    ]
