# Generated by Django 3.0.9 on 2021-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210325_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='user.Role'),
        ),
    ]
