# Generated by Django 3.0.9 on 2021-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='user.Role', verbose_name='rôle'),
        ),
    ]
